### ISSUE TITLE
[BUG] Folder names with regex characters like `[` cause issues

### ISSUE THREAD

**Issue by dinfinity** [regorxxx/Playlist-Manager-SMP#36]
**Describe the bug**
Folder names aren't escaped before using them in a regular expression in `getRelPath()` in `helpers_xxx_playlists_files.js`, leading to obvious issues when folders contain special regex-like characters such as `[`.

The resulting behavior differs depending on how the folder is parsed in the reg exp. For me, the file paths in the produced playlist M3U files were broken.

**Suggested fix**
Just a quick fix for this:
```javascript
function getRelPath(itemPath, relPathSplit) {
	let cache = '';
	relPathSplit.forEach((folder) => {
		const folderEscaped = escapeRegExp(folder);
		const level = new RegExp(folderEscaped + '\\\\', 'i');
		cache = itemPath.replace(level, '');
		if (itemPath === cache) {itemPath = '..\\' + cache;}
		else {itemPath = cache;}
	});
	if (!itemPath.startsWith('..\\')) {itemPath = '.\\' + itemPath;}
	return itemPath;
}

function escapeRegExp(string) {
    return string.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); // $& means the whole matched string
}
```

**Comment by regorxxx** [comment]
Although that solution works most times (there are a few use-cases where it would fail), I prefer a lazier, safer and totally future proof version:

```
const escapeRegExpCache = {};
function escapeRegExp(s) {
	s = toString(s);
	if (s && !escapeRegExpCache.hasOwnProperty(s)) {escapeRegExpCache[s] = s.replace(/([^a-zA-Z0-9])/g, '\\$1');}
	return s ? escapeRegExpCache[s] : s; // Can not be safer than this
}
```
Can't care about readability of the output, since it's all internally used.

Thanks for the report, totally missed this when coding it.

**Comment by dinfinity** [comment]
Thanks for the quick action!
