### ISSUE TITLE
[BUG] Shortcuts don't seem to work in Wine

### ISSUE THREAD

**Issue by sonofevil** [regorxxx/Playlist-Manager-SMP#40]
**Describe the bug**
Perhaps I do not understand how shortcuts are supposed to work, but none of the shortcuts seem to do anything. In particular I am trying to assign cycling through categories to shift+left click on header. But if I shift-click on the header buttons, they just behave as if I had clicked normally.

**To Reproduce**

1. Have at least 2 categories assigned to different playlists.
2. Go to UI -> Shortcuts -> Left click (header) -> Shift
3. Click on "Cycle categories"
4. Shift+left click on any part of the header.
5. The result is the same as without shift.

**Expected behavior**
The playlist manager cycles through the categories.

**Desktop (please complete the following information):**
 - OS: EndeavourOS
 - Browser: IE8 (in Wine)
 - Version: v0.5.0-beta.20

**Additional context**
EndeavourOS is Arch-Linux-based. I am using Foobar2000 v2.0 installed from AUR with Wine 8.7-1 and SMP v1.6.1.

**Comment by sonofevil** [comment]
Correction: Only the header shortcuts are affected.

**Comment by regorxxx** [comment]
I think the most probable case is you have not been using it right. You are not supposed to use header shortcuts everywhere, since that would make zero sense. Read the tooltips. Every single element on the manager shows the available actions ;)

![plm2](https://github.com/regorxxx/Playlist-Manager-SMP/assets/83307074/0aaf0384-dcf8-44f4-80e1-45c0af16d973)

And I will try improve it to make it clearer though, since the menu configuration says header instead of "action button.

Also cycling categories is by default on double click, you don't need to add it to shift too.

**Comment by sonofevil** [comment]
Ah right, I think my issue was that I wasn't even considering the action buttons because, well, they were invisible. I think it's because I'm using a dark theme (black panel backgrounds)? So in order to see them I had to enable "Use background buttons (theme manager)", which I only found out by trying random options since it's a bit cryptic.

**Comment by sonofevil** [comment]
Oh, I have to specifically click the lightning symbol. I see.

**Comment by regorxxx** [comment]
> Ah right, I think my issue was that I wasn't even considering the action buttons because, well, they were invisible. I think it's because I'm using a dark theme (black panel backgrounds)? So in order to see them I had to enable "Use background buttons (theme manager)", which I only found out by trying random options since the meaning of that option wasn't clear to me from the name.

Can you show me your panel with the default UI settings? (colors, and buttons)

**Comment by regorxxx** [comment]
Have edited the menu to point to the specific button:
![image](https://github.com/regorxxx/Playlist-Manager-SMP/assets/83307074/bc6c50ed-c666-435f-aa17-eaaa95b5db0f)

If you disable the search box, then you can also use that part of the header as "action button".
![plm3](https://github.com/regorxxx/Playlist-Manager-SMP/assets/83307074/9e612c63-c195-4bc6-9e30-31a69ff5cbcb)

**Comment by sonofevil** [comment]
> > Ah right, I think my issue was that I wasn't even considering the action buttons because, well, they were invisible. I think it's because I'm using a dark theme (black panel backgrounds)? So in order to see them I had to enable "Use background buttons (theme manager)", which I only found out by trying random options since the meaning of that option wasn't clear to me from the name.
> 
> Can you show me your panel with the default UI settings? (colors, and buttons)

Sorry, I deleted this because I realized it is an unrelated issue. But here:
![Screenshot_20230527_141917](https://github.com/regorxxx/Playlist-Manager-SMP/assets/19374890/b5e2267d-354f-45e2-b176-8b6a3baa57be)

**Comment by sonofevil** [comment]
Actually, I have no idea why, but when I reset "UI" -> "Button toolbar" to the default setting, they are visible just fine. I do not think I changed any theme settings.

**Comment by sonofevil** [comment]
Okay, I created a new panel to check the behavior, and they actually start invisible (presumably black on black). But then when I change the setting, and afterwards return it to default, they remain visible.
