### ISSUE TITLE
Toolbar buttons are initially invisible on a dark panel theme

### ISSUE THREAD

**Issue by sonofevil** [regorxxx/Playlist-Manager-SMP#41]
If background is set to black and text to white in Foobar2000's default UI settings, and a new SMP panel with Playlist Manager is created, the toolbar buttons at the bottom are initially invisible. This is affected by the "UI" -> "Button Toolbar..." setting:

> Okay, I created a new panel to check the behavior, and they actually start invisible (presumably black on black). But then when I change the setting, and afterwards return it to default, they remain visible. So the problem is permanently resolved for a given panel after changing the setting once.

_Originally posted by @sonofevil in https://github.com/regorxxx/Playlist-Manager-SMP/issues/40#issuecomment-1565393558_

This behavior was observed on Linux with Wine 8.7-1

**Comment by regorxxx** [comment]
Will try to look for a workaround. Thanks

**Comment by regorxxx** [comment]
[Playlist-Manager-SMP-0-5-0-beta21-package.zip](https://github.com/regorxxx/Playlist-Manager-SMP/files/11594415/Playlist-Manager-SMP-0-5-0-beta21-package.zip)
Try this one, let me know if it works in your side too.

**Comment by sonofevil** [comment]
> [Playlist-Manager-SMP-0-5-0-beta21-package.zip](https://github.com/regorxxx/Playlist-Manager-SMP/files/11594415/Playlist-Manager-SMP-0-5-0-beta21-package.zip) Try this one, let me know if it works in your side too.

It works. 👌
