### ISSUE TITLE
[FEATURE] Pinned playlists

### ISSUE THREAD

**Issue by sonofevil** [regorxxx/Playlist-Manager-SMP#43]
**Is your feature request related to a problem? Please describe.**
Manual sorting is not yet possible.

**Describe the solution you'd like**
A simple way to make managing a large number of playlists easier might be to allow pinning selected playlists to the top of the list. This could make operations like frequent moving of files from temporary to permanent (i.e. how long a playlist is used before it is deleted) playlists easier. Implementation seems straightforward for physical playlists. I don't know if there is a good way to implement this for UI-only playlists. But as a physical-only feature it could still be quite helpful.

**Describe alternatives you've considered**
Creating a category for playlists one might otherwise want to pin, and then switching categories (or filtering) as needed. However, this is very inconvenient for the use case described above.

Another alternative would be to utilize tags. Create a "_pinned" tag and then select sorting by tags. Problem: This currently makes it impossible to use other sorting schemes at the same time. Same goes for using name prefixes and then sorting by name. By contrast, a pinning feature could take priority over the selected sorting scheme, such that pinned and unpinned playlists are first separated in the UI and then sorted separately.

**Comment by regorxxx** [comment]
It should work now on UI-only playlists.

**Comment by sonofevil** [comment]
Awesome.

**Comment by regorxxx** [comment]
Added sorting submenu on 9bdf5b3c29af1cff3f1a34d6e0eeede9117ac0b7
