### ISSUE TITLE
[FEATURE] New playlist from selection

### ISSUE THREAD

**Issue by sonofevil** [regorxxx/Playlist-Manager-SMP#45]
**Is your feature request related to a problem? Please describe.**
I honestly thought this feature was previously present, but maybe my memory is playing tricks on me. Anyway, I frequently create new playlists from selected tracks. In the default playlist manager, this can easily be done by dragging the tracks into the playlist manager. A new playlist will be created according to a default title formatting scheme that can be customized in the settings. PM-SMP doesn't have this.

**Describe the solution you'd like**
I don't necessarily need the drag-drop functionality. But it would be very useful to have an option in the list menu that acts like this. Just add the selected tracks to a new playlist and automatically generate the title (personally I'd be happy with "%album-artist% - %album%", but customization would ofc be great).

**Describe alternatives you've considered**
"Create new playlist file from active playlist..." takes the whole playlist and just copies its title. A "Move selection to playlist" shortcut requires that a named playlist already exists.

**Comment by regorxxx** [comment]
Drag n drop already allows to create a playlist. Read the pdf.

Don't see the point of the customizable TF. If you are adding all tracks from single album, great. But a TF expression makes zero sense as soon as you have other use-cases. Not adding that kind of complexity.

Will consider the menu entry.

**Comment by sonofevil** [comment]
> Drag n drop already allows to create a playlist. Read the pdf.
> 
> Don't see the point of the customizable TF. If you are adding all tracks from single album, great. But a TF expression makes zero sense as soon as you have a mix of random tracks or other use-cases. Not adding that kind of complexity.
> 
> Will consider the menu entry.

You're right, I didn't realize there were drag and drop key combos. That makes the feature request superfluous as far as I'm concerned. Thanks.

**Comment by sonofevil** [comment]
However, I just noticed that the title isn't automatically generated. So I guess that part would still be an improvement.
