### ISSUE TITLE
[BUG] "Playlist generation failed" when removing all tracks from playlist

### ISSUE THREAD

**Issue by sonofevil** [regorxxx/Playlist-Manager-SMP#46]
**Describe the bug**
Today I synced the scripts with Github, and now whenever I remove all tracks from a playlist, a few seconds later it throws the "playlist generation failed" error (see screenshot).

Otherwise everything works as expected. The file is in reality updated just fine.

Might be related to my other issue, not sure. But UUIDs for playlist names is disabled. It's reproducible on a new SMP panel. Bug probably was introduced between June 6 and now.

**To Reproduce**
1. Create an empty playlist called "test".
2. Add some tracks to it.
3. Remove all the tracks from it.
4. Wait for error.

**Expected behavior**
No error.

**Screenshots**
![Screenshot_20230617_182022](https://github.com/regorxxx/Playlist-Manager-SMP/assets/19374890/53a85bfb-c149-4cce-8e31-55580bdbfb26)

**Desktop (please complete the following information):**
 - OS: EndeavourOS & Wine 8.9-1
 - Browser: Wine browser
 - Version: Latest Github clone

**Comment by regorxxx** [comment]
Not reproducible; up to now, you are the only one reporting these errors, so it looks like something on your side.

Check file/folder permissions (?)

**Comment by regorxxx** [comment]
> . The file is in reality updated just fine.
Also told you to check the recycle bin (?). Because that popup only appears when the file is not deleted properly (before overwriting). Also covered in the pdf.

Check it, and let me know.

**Comment by regorxxx** [comment]
Fixed a writing error today, which I don't know if it was the problem you were having:
https://github.com/regorxxx/Playlist-Manager-SMP/commit/b51b6b00291b633d9bed3bacc41b1ad482e6d210

It required a specific position.

Also added more extensive popups and logging errors here:
https://github.com/regorxxx/Playlist-Manager-SMP/commit/8e86499a74e161c0a62cdc83891e845b8e2bc6d6

Which may come handy to find your problem...

**Comment by sonofevil** [comment]
> > . The file is in reality updated just fine.
> 
> Also told you to check the recycle bin (?). Because that popup only appears when the file is not deleted properly (before overwriting). Also covered in the pdf.
> 
> Check it, and let me know. I know you said the trash was working, but it's clearly not working as intended. There is something really weird on your wine config not compatible with this; but other wine users had not experienced any of this, so can't really help with it anymore. This will require a lot of testing

Thing is, I created a new wineprefix not long ago and didn't really change anything, except for applying fixes from the Playlist Manager documentation. Permissions on all files and folder inside the wineprefix is rw for my user, and the same thing goes for my user profile. It's all on the same partition, which does have a working trash folder, and when I delete playlists they are moved there just fine. The trash folder also has rw permission and is owned by me, though lacks "group" and "others" permissions. (P sure this is default for Linux trash. I once had an issue getting trash to work on ntfs and it was solved by mounting it with those exact perms.) 

I hope the update allows me to narrow down the problem further. Sorry my Linux is so weird.

**Comment by regorxxx** [comment]
Since you were able to reproduce it with specific steps, let me know if now works. Otherwise paste the error and logs.

And then I will provide you modified files with extensive logging to find the exact line of code failing on wine.

**Comment by sonofevil** [comment]
After updating the scripts from Github, the error no longer appears. Seems solved.
