### ISSUE TITLE
[BUG] Playlists from selection are empty - "Index out of bounds"

### ISSUE THREAD

**Issue by sonofevil** [regorxxx/Playlist-Manager-SMP#48]
**Describe the bug**
Any new playlist created from selected tracks via drag & drop or menu is empty and accompanied by console errors like this:

`[10:23:56 PM] Playlist Manager: Error adding tracks to playlist. Index (118) out of bounds. (sendSelectionToPlaylist)`

118 seems to be the number of playlists I have. Looks like it's too many for the script to handle, though it doesn't prevent me from creating playlists, they are just empty for some reason. I can still subsequently add tracks manually.

I know that's a lot of playlists, and that may make it a somewhat rare use case, but it's not just unused junk, they are actually all part of how I manage my music library. But I'm considering ways to reduce the number.

**To Reproduce**
1. Have 118 playlists.
2. Select some tracks.
3. In the playlist menu click "Create new playlist from selection..."
4. Observe new playlist being empty and error in console.log.

**Expected behavior**
New playlist contains the selected tracks.

**Desktop (please complete the following information):**
- OS: EndeavourOS & Wine 8.9-1
- Browser: Wine browser
- Version: Latest Github clone

**Comment by regorxxx** [comment]
It has nothing to do with number, there is not a limit. 

You have a filter enabled and the new playlist created was not in that view, so it the index found was not valid.
