### ISSUE TITLE
UI for settings

### ISSUE THREAD

**Issue by stephen147** [regorxxx/Playlist-Manager-SMP#50]
I've just installed this and finding it impossible to set this up without a UI.

The menu just disappears and you have to start all over again to go through the menu. 

Probably a huge undertaking to do.

**Comment by regorxxx** [comment]
I don't understand your request. No one has had any problems using menus up to now.

Please send screnshots/gif about your problem.

I don't plan to use HTML popups; I want this to be wine compatible.

**Comment by stephen147** [comment]
Nevermind. I found a similar playlist manager to the old [foo_plorg](https://hydrogenaud.io/index.php/topic,80705.0.html) [here](https://hydrogenaud.io/index.php/topic,123820.0.html). It imported all the old PLs into it. 

Given the complexity of your settings for the manager, I think having to navigate through menus to change settings is difficult. Is there a text file of some sort to change settings?

If your manager could import all the old playlists from the old foo_plorg then I may give it a go when I have the time.

**Comment by regorxxx** [comment]
As you can imagine, it's your work to read the documentation; if you are fine with another script, then great.

It makes no sense for me to compare both managers since the range of features on foo_plorg or the JS version is so different to this. This is what it is and I'm fine with some people preferring a simpler approach or who only need UI playlists.

**Comment by regorxxx** [comment]
In any case, next update will have a lite mode which will only work with UI-only playlists (and reduce most advanced features to a minimum), serving as a replacement for foo_plorg. 

But this script doesn't try to serve as a copy of it but as a full replacement/improvement to it. So I have zero interest on importing things from it.
