### ISSUE TITLE
Left click activate / Right click menu on selected

### ISSUE THREAD

**Issue by stephen147** [regorxxx/Playlist-Manager-SMP#51]
Can this be possible to allow a left click to load the playlist?

Currently, the double left click is buggy and doesn't load the playlist most of the time. As far as I can see the RMB does nothing so can it be mapped to show the menu? Pretty sure this is better UIX.

**Comment by regorxxx** [comment]
Dbl click is not "buggy", adjust the timer to suit your needs.

About your request, I think you have not read the pdf, since mouse actions are fully configurable.

**Comment by stephen147** [comment]
When I checked the options yesterday there was no Left Click>Single Click option for some reason. Now it's showing. 

Actually going to revert to this manager as the other one I mentioned it way to slow when loading foobar.

Thanks for this.

**Comment by regorxxx** [comment]
Uhm, maybe you were using an old version. L. click is available on last version.

There is something wrong on your install, the package must be 40MB aprox. and obviously you need a PDF reader. It's working fine on all my systems.

Also, read the tooltip of the help button. I think that's what you are looking for.
![image](https://github.com/regorxxx/Playlist-Manager-SMP/assets/83307074/8e3d8d08-efac-49e4-8cb5-4ac3a37aced0)
