### ISSUE TITLE
Search filter active - Cloning / deleting playlist, filter no longer works

### ISSUE THREAD

**Issue by stephen147** [regorxxx/Playlist-Manager-SMP#55]
See this. Also doesn't work when you filter and when there are say 10 items showing and you delete a playlist then the filter does the same. 

This may be true for other things also but these are the ones I noticed.

![2023 07 01 (20-36-31)](https://github.com/regorxxx/Playlist-Manager-SMP/assets/14054664/a7c609c0-45ac-447f-b09e-3c7c6c864dce)

**Comment by regorxxx** [comment]
Reproduced. Thanks!
