### ISSUE TITLE
[FEATURE] Remember search filter on next startup

### ISSUE THREAD

**Issue by stephen147** [regorxxx/Playlist-Manager-SMP#56]
This. Setting to remember the last used filter after launching again.

![image](https://github.com/regorxxx/Playlist-Manager-SMP/assets/14054664/6e197da4-b65c-4996-80da-ddf09fa907a8)

**Comment by regorxxx** [comment]
Why? 
Search is not meant to be permanent. No panel on foobar has a permanent search filter. The other filters are.

**Comment by stephen147** [comment]
As a preference would be nice. Default to not.

I'd prefer to continue where I left off.

**Comment by regorxxx** [comment]
I see no reason to do it for my own usage so not going to happen in my free time. Have no motivation for it (even if I agree it's a good request).

**Comment by stephen147** [comment]
Just think it would be nice have and just because something isn't in FB doesn't mean it's correct.
