### ISSUE TITLE
[BUG]  After editing a query if the item is not centred vertically, jumps to the centre

### ISSUE THREAD

**Issue by stephen147** [regorxxx/Playlist-Manager-SMP#58]
As the title. The scrollbar jumps so the edited playlist is centred vertically.

Scrolling shouldn't be affected unless you use the mouse scroll wheel.

![2023 07 09 (16-16-58)](https://github.com/regorxxx/Playlist-Manager-SMP/assets/14054664/cc6dfced-ecc7-4ad3-a072-a0e2026db586)

**Comment by regorxxx** [comment]
Fixed.

**Comment by stephen147** [comment]
Cheers.
