### ISSUE TITLE
helpers_xxx_flags.js is gone

### ISSUE THREAD

**Issue by ASopH** [regorxxx/Playlist-Manager-SMP#6]
Hi, I think a file was lost after update to the lastest..

Error: Spider Monkey Panel v1.6.0 (Playlist Manager: Playlist Manager v0.5.0 by XXX)
include failed:
include failed:
Path does not point to a valid file: helpers_xxx_flags.js

File: buttons_panel_xxx.js
Line: 6, Column: 1
Stack trace:
  @buttons_panel_xxx.js:6:1
  @playlist_manager.js:13:1

after update to the latest plm

regards :-)

**Comment by regorxxx** [comment]
Missed the file while updating ups... Fixed! Thanks ;)
