### ISSUE TITLE
[BUG] Same filter in foobar2000 doesn't work in PM

### ISSUE THREAD

**Issue by stephen147** [regorxxx/Playlist-Manager-SMP#60]
Using this in fb works:
`%ALBUMARTISTSORT%%ALBUMTYPE%%ARTISTS%%ARTISTSORT%%ARTWORKGUID% PRESENT`

But I get this error with PM SMP
```
Query not valid:
%ALBUMARTISTSORT%%ALBUMTYPE%%ARTISTS%%ARTISTSORT%%ARTWORKGUID% PRESENT
```

EDIT:
Same with
`%COMPOSERSORT% PRESENT` & `%GENRESORT% PRESENT`

**Comment by regorxxx** [comment]
The 'SORT' part within ARTISTSORT was the problem. Fixed.
