### ISSUE TITLE
[FEATURE] Search history remember after each session

### ISSUE THREAD

**Issue by stephen147** [regorxxx/Playlist-Manager-SMP#61]
Just like the find box in windows. Thanks.

![image](https://github.com/regorxxx/Playlist-Manager-SMP/assets/14054664/68980be2-4361-427f-bc10-d4b0a25b2177)

**Comment by stephen147** [comment]
I'll just amend this to allow the history to be remembered after each session and not get lost.

**Comment by regorxxx** [comment]
You have the search history on the button.

**Comment by stephen147** [comment]
Seems a little strange that the search history isn't remembered when you start fb2k again and it's cleared and the feature seems a little half baked.
