### ISSUE TITLE
[BUG] Renaming of playlist

### ISSUE THREAD

**Issue by stephen147** [regorxxx/Playlist-Manager-SMP#64]
The path of the file is:
`W:\Apps (Portable)\Music Apps\foobar2000\profile\playlist_manager\_Get - Buy FLAC and Remaining FLACs.m3u8`

But it returns this error message:
```
Error renaming playlist file: _Get / Buy FLAC and Remaining FLACs --> _Better: _Get / Buy FLAC and Remaining FLACs

Old Path: W:\Apps (Portable)\Music Apps\foobar2000\profile\playlist_manager\_Get - Buy FLAC and Remaining FLACs.m3u8
New Path: W:\Apps (Portable)\Music Apps\foobar2000\profile\playlist_manager\_Better _Get \ Buy FLAC and Remaining FLACs.m3u8

Restoring backup...
```

It then creates an empty folder with the path:
`W:\Apps (Portable)\Music Apps\foobar2000\profile\playlist_manager\_Better Get`

Seems the new path isn't getting escaped properly.

**Comment by regorxxx** [comment]
You are using not standard hyphen unicode chars.

**Comment by stephen147** [comment]
Thanks for fixing it.

The `-` I was using was `U+002D : HYPHEN-MINUS {hyphen, dash; minus sign}`.

I checked it here https://www.babelstone.co.uk/Unicode/whatisit.html
