### ISSUE TITLE
[BUG] Performance issues

### ISSUE THREAD

**Issue by sonofevil** [regorxxx/Playlist-Manager-SMP#65]
**Describe the bug**
The panel is very slow and unresponsive on my laptop after recent updates, when previously it worked smoothly. I turned off background images, but it didn't help.

**To Reproduce**
1. Run PM-SMP in Wine on a device with similar specs.

**Expected behavior**
Script runs smoothly.

**Screenshots**
Visual changes are slow and unresponsive (I'm getting maybe like 4 frames per second and there is a very noticeable delay between any interaction and response).

**Desktop (please complete the following information):**
 - Device: ThinkPad t440s
 - Processors: 4 × Intel® Core™ i5-4300U CPU @ 1.90GHz
 - Memory: 7,5 GiB of RAM
 - Graphics Processor: Mesa Intel® HD Graphics 4400
 - OS: EndeavourOS
 - Browser: Wine browser
 - Version: Latest git clone.
 - Wine version: wine-8.9

**Comment by sonofevil** [comment]
None of my system resources is actually maxed out so idk what's going on.

**Comment by regorxxx** [comment]
Redownload the package.

**Comment by sonofevil** [comment]
> Redownload the package.

No difference, regardless of whether I use release v0.5.0-beta.25 or a git clone.

**Comment by regorxxx** [comment]
Can not reproduce it, try it on a new clean portable install.

**Comment by regorxxx** [comment]
![image](https://github.com/regorxxx/Playlist-Manager-SMP/assets/83307074/7a40d978-d739-4974-b555-3847dca4c48d)

**Comment by sonofevil** [comment]
On a clean, portable installation, the performance decreases as the number of displayed playlists increases. If I have the same number of playlists displayed as on my old installation, the performance becomes just as slow. It doesn't matter which wineprefix I use either.

**Comment by regorxxx** [comment]
I don't really understand your problem. I mean, with 10 playlists shown on the list it has zero impact on windows. Not sure what your numbers are.

The manager may track thousands of playlists, but the actual playlists shown can not be so high anyway. Please show a gif and paste your properties. If this was a SMP performance problem it would have appeared before too, but you said it only happens on new versions (?).

There has been no change on UI related to performance except the shadow on text which can be disabled.

**Comment by regorxxx** [comment]
Also I'm not sure about your last reply. You say:
> If I change the filters so that fewer playlists are displayed, it becomes faster.

These are the playlists displayed.
![image](https://github.com/regorxxx/Playlist-Manager-SMP/assets/83307074/50903620-c2a9-4b8b-8dc1-820c21d736b4)

It doesn't matter which filter you use, as long as there are more playlists than the current height, no more can be shown and thus they don't affect performance at all.

Now if you are talking about the panel total playlists tracked... that's an entirely different problem than the one described. I have 100 playlist on a panel without any performance problem.

**Comment by sonofevil** [comment]
> I don't really understand your problem. I mean, with 10 playlists shown on the list it has zero impact on windows. Not sure what your numbers are.
> 
> The manager may track thousands of playlists, but the actual playlists shown can not be so high anyway. Please show a gif and paste your properties. If this was a SMP performance problem it would have appeared before too, but you said it only happens on new versions (?).
> 
> There has been no change on UI related to performance except the shadow on text/art background [both] which can be disabled.

I only have 28 playlists displayed right now. It becomes noticeably slower with every added playlist.

I have all fancy effects in the settings set to disabled. I'm not sure how to enable or disable text shadow and I can't find "shadow" mentioned in the docs.

[vokoscreenNG-2023-07-31_12-38-11.webm](https://github.com/regorxxx/Playlist-Manager-SMP/assets/19374890/8e88003d-a7a6-4a24-891b-4f8af50c7101)

**Comment by sonofevil** [comment]
Well this is strange. I did some testing on 0.5.0 beta 20, and unlike my previous experience it is also slow, but the performance issue immediately disappears if I disable "show name/category separators" (perhaps I had it disabled in the past). However, this does not work with v0.5.1. Here I cannot find any setting that noticeably impacts performance.

**Comment by regorxxx** [comment]
It may be that wine performance is heavily affected by some SMP drawing methods then.

I'm going to disable shadows (by default) whenever art background is also disabled, since both are meant to be used together. And then add some kind of warning either via popups or docs about this.

Now, if you are interested in further testing, I could provide you some test files to try to find an alternate method to create the shadows while also being fine on wine.

**Comment by regorxxx** [comment]
Nevermind, optimized it. If there is any problem now, it's a SMP performance problem; can not be optimized anymore.

**Comment by sonofevil** [comment]
> It may be that wine performance is heavily affected by some SMP drawing methods then.
> 
> I'm going to disable shadows (by default) whenever art background is also disabled, since both are meant to be used together. And then add some kind of warning either via popups or docs about this.
> 
> Now, if you are interested in further testing, I could provide you some test files to try to find an alternate method to create the shadows while also being fine on wine. On windows there is no difference at all with shadows...

Sorry for the late reply. Wine performance has some weird random issues with seemingly harmless things. For example if you open the settings page for Foobar2000 keyboard shortcuts, it takes forever to load, and freezes every time you type something in the search box. This issue hasn't gone away in 5+ years. So yeah, not surprised that Wine struggles with some things in SMP.

**Comment by regorxxx** [comment]
I have found some performance problems related to columns usage (they were being calculated on every paint call), they should be fixed now on latest commits. Maybe that was also impacting your setup.
