### ISSUE TITLE
[BUG] Track count lags one step behind reality

### ISSUE THREAD

**Issue by sonofevil** [regorxxx/Playlist-Manager-SMP#67]
**Describe the bug**
When I ctrl+drag tracks into an UI-only playlist, the track count is shown incorrectly. After dropping the tracks, the displayed track count is the one from before adding the tracks.

**To Reproduce**
1. Ctrl+drag some tracks into an UI-only playlist.
2. Observe the wrong track count next to the playlist title.

**Expected behavior**
Track count will always show the actual number of tracks in the playlist.

**Screenshots**
![Screenshot_20230719_005248](https://github.com/regorxxx/Playlist-Manager-SMP/assets/19374890/22c2ba26-8ec1-4d95-a720-4ea8e53df013)

**Desktop (please complete the following information):**
 - OS: EndeavourOS
 - Browser: Wine browser
 - Version: git clone latest

**Comment by regorxxx** [comment]
Fixed.
