### ISSUE TITLE
[BUG] Fuzzy text for playlist name

### ISSUE THREAD

**Issue by stephen147** [regorxxx/Playlist-Manager-SMP#69]
This sometimes happens on startup or after a while.

It's hard to say what causes it.

![image](https://github.com/regorxxx/Playlist-Manager-SMP/assets/14054664/24fc6d47-f2de-42b4-bcbc-cd60c6fa2c7a)

**Comment by regorxxx** [comment]
Disable text shadows.

Will fix it on next version.

**Comment by regorxxx** [comment]
Fixed on last release.
