### ISSUE TITLE
Removed playlist inside folder not removed from UI [BUG] 

### ISSUE THREAD

**Issue by sonofevil** [regorxxx/Playlist-Manager-SMP#72]
**Describe the bug**
Removing a playlist that is inside a folder does not properly update the UI. The entry remains visible until Foobar2000 is restarted or the panel is reloaded. Trying to open it yields an error.

**To Reproduce**
1. Delete a playlist that is inside a folder via the UI (e.g. right click -> delete).
3. Double-click/attempt to open the residual UI entry.
3. See error.

```
Playlist file does not exist: Autopsy - Ashes
Path: Z:\home\lutra\.foobar2000\profile\playlist_manager\Autopsy - Ashes_ts_Tue_Jan_02_20241704227579806.m3u8
```

**Expected behavior**
The UI item disappears once the playlist is deleted.

**Desktop (please complete the following information):**
 - OS: Arch linux / Wine
 - Browser: wine browser
 - Version 0.12.1

**Comment by regorxxx** [comment]
This is already fixed I think. At least on the current state of the script, not sure about the release.
https://github.com/regorxxx/Playlist-Manager-SMP/wiki/Nightly-releases

Please check it with that nightly package. I have not been able to reproduce it.

**Comment by sonofevil** [comment]
The nightly seems to be broken for me, even if I try to do a clean install:

```
Error: Spider Monkey Panel v1.6.1 ({EAFC5F08-C868-44F4-9723-52B2428B5AC1}: Playlist-Manager-SMP v0.12.1 by Regorxxx)
include failed:
include failed:
include failed:
include failed:
value is null

File: helpers_xxx_prototypes.js
Line: 153, Column: 15
Stack trace:
  roughSizeOfObject@helpers_xxx_prototypes.js:153:15
  _save@helpers_xxx_file.js:295:12
  @helpers_xxx_tags_cache.js:30:1
  @remove_duplicates.js:32:18
  @playlist_manager_helpers.js:31:1
  @playlist_manager_list.js:37:1
  @main.js:38:1

```

**Comment by regorxxx** [comment]
Should be fixed now, check package created automatically in 10 min.
