### ISSUE TITLE
Certain folder expanding/contracting arrangements make the panel crash [BUG] 

### ISSUE THREAD

**Issue by sonofevil** [regorxxx/Playlist-Manager-SMP#73]
**Describe the bug**
I have noticed that I cannot expand two folders at the same time. Under certain conditions, trying to do this makes the panel crash.

**To Reproduce**
1. Create two folders and add several playlists to each.
2. Expand the second folder.
3. Expand the first folder. Observe the second folder's contents becoming invisible (arrow still indicating that its expanded).
4. Click the arrow on the second folder to make the panel crash.

```
Error: Spider Monkey Panel v1.6.1 ({51BD717E-C3E5-4A68-9A09-70BCF60AB155}: Playlist-Manager-SMP v0.12.1 by Regorxxx)
this.data[i] is undefined

File: playlist_manager_list.js
Line: 3881, Column: 11
Stack trace:
  _list/this.switchFolder@playlist_manager_list.js:3881:11
  _list/this.lbtn_up@playlist_manager_list.js:1717:15
  @main.js:591:9
  fireEvents/</<@callbacks_xxx.js:149:37
  fireEvents/<@callbacks_xxx.js:145:30
```

**Expected behavior**
Expanded folders contents remain visible until they are manually contracted.

**Screenshots**
![Screenshot_20240102_215126](https://github.com/regorxxx/Playlist-Manager-SMP/assets/19374890/15f26761-d22e-4c68-939a-916e67ff9b44)

**Desktop (please complete the following information):**
 - OS: Arch Linux/Wine
 - Browser: Wine browser
 - Version: 0.12.1

**Comment by regorxxx** [comment]
Have been able to reproduce this one, will check it.

**Comment by regorxxx** [comment]
Managed to fix it and some other possible similar situations due to wrong coding of the folder recursion.

Again, wait 10 min to get the refreshed package.
