### ISSUE TITLE
"Shortcut not properly set: M Single Click --> Copy selection to playlist" [BUG] 

### ISSUE THREAD

**Issue by sonofevil** [regorxxx/Playlist-Manager-SMP#74]
**Describe the bug**
I set the single middle click to "copy selection to playlist", but it doesn't work and produces an error.

**To Reproduce**
1. Configure middle click to "copy selection to playlist".
2. Select some tracks.
3. Middle-click on a playlist.

`Shortcut not properly set: M Single Click --> Copy selection to playlist`

**Expected behavior**
Selected tracks are copied to the playlist I click on.

**Desktop (please complete the following information):**
 - OS: EndeavourOS/Wine
 - Browser: Wine browser
 - Version: 0.12.1

**Additional context**
I tried installing the latest Nightly, but it gets stuck on "loading" when I start Foobar2000 and is thus unusable, so this is still the standard release.

Note that it works just fine with ctrl+middle click.

**Comment by regorxxx** [comment]
Nightly not working must be an error on your side, just reload the panel. It's working fine here. Both as package and script file.

Also delete anything at '\foobar2000\js_data\temp\'

**Comment by sonofevil** [comment]
> Nightly not working must be an error on your side, just reload the panel. It's working fine here. Both as package and script file.
> 
> Also delete anything at '\foobar2000\js_data\temp'

It seems to happen even with a totally clean install.

**Comment by regorxxx** [comment]
Have found the problem with the bug (and will fix it asap), but no idea with the package thing, since I can not reproduce it in any way. 

Maybe redownload it?
For ex. this one works fine:
https://github.com/regorxxx/Playlist-Manager-SMP/actions/runs/7411092033

**Comment by sonofevil** [comment]
> Also, I need more info. Send me your console and a gif. The tooltip shows the current action if its 'loading' or 'updating'

The log gets stuck here:

	```
https://raw.githubusercontent.com/Regorxxx/Playlist-Manager-SMP/main/VERSION
[9:25:43 PM] Playlist Manager: created dynamic menus
[9:25:44 PM] Playlist manager: Cached playlists for searching
[9:26:19 PM] Playlist manager: reading files from "Z:\home\lutra\.foobar2000\profile\playlist_manager\"
[9:26:21 PM] Spider Monkey Panel v1.6.1: profiler ({AAF59FDB-61BD-46AD-AB04-2B4F509EB087}: loadPlaylistsFromFolder): 1475ms
[9:26:22 PM] Caching library paths 0%.
[9:26:22 PM] Caching library paths 10%.
[9:26:24 PM] Caching library paths 20%.
[9:26:25 PM] Caching library paths 30%.
[9:26:26 PM] Playlist Manager: created dynamic menus
[9:26:26 PM] Caching library paths 40%.
[9:26:27 PM] Caching library paths 50%.
[9:26:37 PM] Playlist manager: Cached playlists for searching
[9:27:55 PM] getText(): undefined
	https://raw.githubusercontent.com/Regorxxx/Playlist-Manager-SMP/main/VERSION
```

![Screenshot_20240104_212836](https://github.com/regorxxx/Playlist-Manager-SMP/assets/19374890/90748c50-c736-4dc1-a7ee-69f84640275b)

Hope that is sufficiently informative, I don't have any gif creation tools installed.

**Comment by regorxxx** [comment]
I need the tooltip over the panel though

**Comment by regorxxx** [comment]
That's an entirely different problem, so opening a new issue for that.

 This one has been fixed.

**Comment by sonofevil** [comment]
Sorry, I was out of commission yesterday.
