### ISSUE TITLE
[BUG]  Infinite panel loading on init (nightly)

### ISSUE THREAD

**Issue by regorxxx** [regorxxx/Playlist-Manager-SMP#75]
**Describe the bug**
Infinite panel loading on init.

**Screenshots**

> https://raw.githubusercontent.com/Regorxxx/Playlist-Manager-SMP/main/VERSION
> [9:25:43 PM] Playlist Manager: created dynamic menus
> [9:25:44 PM] Playlist manager: Cached playlists for searching
> [9:26:19 PM] Playlist manager: reading files from "Z:\home\lutra\.foobar2000\profile\playlist_manager\"
> [9:26:21 PM] Spider Monkey Panel v1.6.1: profiler ({AAF59FDB-61BD-46AD-AB04-2B4F509EB087}: loadPlaylistsFromFolder): 1475ms
> [9:26:22 PM] Caching library paths 0%.
> [9:26:22 PM] Caching library paths 10%.
> [9:26:24 PM] Caching library paths 20%.
> [9:26:25 PM] Caching library paths 30%.
> [9:26:26 PM] Playlist Manager: created dynamic menus
> [9:26:26 PM] Caching library paths 40%.
> [9:26:27 PM] Caching library paths 50%.
> [9:26:37 PM] Playlist manager: Cached playlists for searching
> [9:27:55 PM] getText(): undefined
> 	https://raw.githubusercontent.com/Regorxxx/Playlist-Manager-SMP/main/VERSION

![image](https://github.com/regorxxx/Playlist-Manager-SMP/assets/83307074/75c0269b-2411-4fb5-bf07-9f622a3edefa)

**Additional context**
https://github.com/regorxxx/Playlist-Manager-SMP/issues/74#issuecomment-1877479578

**Comment by regorxxx** [comment]
@sonofevil

**Comment by regorxxx** [comment]
Ok, I use 2 panels, and restarting foobar shows this problem in one of them. Will investigate it since I don't remember touching anything related to this part of the code... but it didn't happened before.

I have done an extended code cleanup in the last weeks, so maybe I touched something.

**Comment by regorxxx** [comment]
What's the size of your library?
What's the size of your playlist folder?

I need more info.

Can't reproduce it on single panel usage.

**Comment by sonofevil** [comment]
Sorry, I was out of commission for a while.

Latest nightly still produces the exact same behavior for me as before. Probably irrelevant but I selected "no" for lite mode and "yes" to every other prompt during setup. Clean install.

Tooltip says: 
```
Caching library paths... 
Panel will be disabled during the process.
```
@regorxxx

**Comment by sonofevil** [comment]
Wait nevermind, the package linked in README.md apparently wasn't the latest. It works just fine with this one: https://github.com/regorxxx/Playlist-Manager-SMP/actions/runs/7415872075
