### ISSUE TITLE
"Don't ask again" option for UI-playlist deletion prompt [FEATURE]

### ISSUE THREAD

**Issue by sonofevil** [regorxxx/Playlist-Manager-SMP#76]
**Is your feature request related to a problem? Please describe.**
I create a lot of playlists and I delete a lot of playlists on the daily. This is something I would like to streamline somewhat.

**Describe the solution you'd like**
A "don't ask again" kind of option would be nice to have for the prompt that asks whether the UI-only playlist should also be deleted when deleting a "physical" playlist.

**Comment by regorxxx** [comment]
Done, check nightly to test it.

**Comment by sonofevil** [comment]
Thanks!
