### ISSUE TITLE
[FEATURE] - Search all tags in autoplaylist

### ISSUE THREAD

**Issue by stephen147** [regorxxx/Playlist-Manager-SMP#77]
In previous versions AFAIK (it maybe didn't throw an error) but you could have autoplaylist with a string but not now, as it's warning me that these are invalid.

![image](https://github.com/regorxxx/Playlist-Manager-SMP/assets/14054664/b7aed523-2d3c-4e8e-a074-c4844312c4da)

![image](https://github.com/regorxxx/Playlist-Manager-SMP/assets/14054664/5b369ec4-014e-48c6-9f71-ad23c7836734)

**Comment by regorxxx** [comment]
And what's the problem? That's not a valid query (?)

**Comment by stephen147** [comment]
Thanks for adding this. Sorry only got around to upgrading the component and "* HAS ’" works just fine.

**Comment by regorxxx** [comment]
Simple search should also work -again- since January 26 btw
