### ISSUE TITLE
[FEATURE] Convert UI-playlist to physical playlist

### ISSUE THREAD

**Issue by sonofevil** [regorxxx/Playlist-Manager-SMP#79]
**Is your feature request related to a problem? Please describe.**
Right clicking something in the library and selecting "Send to new playlist" is generally faster than using the tools provided by the script, but this only creates UI-only playlists. Those can be "cloned" as physical playlists, but that creates redundant clutter.

**Describe the solution you'd like**
A context menu option to convert an UI-only-playlist to a playlist associated with a playlist file tracked by the script.

**Comment by sonofevil** [comment]
Oh and if possible, it would be amazing if this could be done with multiple selected UI playlists at once.

**Comment by regorxxx** [comment]
Currently you only have to use ¡create new playlist from active¡, and it gets converted to a physical playlist. It's on the + menu, not the contextual menu. It does what you want.

But as you noted there is no way to do it for any selected playlist, you have to make it active first. And there is no way to do it in batch. I will look for your suggestion.

Ideally, I would like to implement a mode which automatically converts every UI playlist into a file. But then there would be no way to differentiate between "closing" a playlist and "deleting" it.

**Comment by regorxxx** [comment]
Finally about using the library manager being faster, you can currently just drag n drop tracks and they can be send to a new playlist directly.

I may also add a faster method to create a playlist, by pressing shit and clicking on the + button. Which would be equivalent to drag n drop selected tracks into a new playlist. Or configurable shortcuts at the bolt button.

**Comment by sonofevil** [comment]
> Currently you have to use 'create new playlist from active', and it gets converted to a physical playlist. It's on the + menu, not the contextual menu. It does what you want.

Doesn't seem to. The old UI playlist still exists afterwards.

**Comment by regorxxx** [comment]
> Doesn't seem to. The old UI playlist still exists separately afterwards.
Thad doesn't happen if you use the same name.

All other things implemented.

**Comment by sonofevil** [comment]
Thank you.
