### ISSUE TITLE
[BUG] tracks in .m3u8 playlists cannot play

### ISSUE THREAD

**Issue by stephen147** [regorxxx/Playlist-Manager-SMP#82]
When in a .m3u8 playlist and clicking a track, it doesn't play.

**System info:**
 - OS: Windows 10 Pro (Build 19045)
 - Related software: ![image](https://github.com/regorxxx/Playlist-Manager-SMP/assets/14054664/1f7b04ee-89b4-4619-b2a8-5e4bef09956a)
 - Github release: Latest version.

**Comment by regorxxx** [comment]
I don't think that's related at all to my plugin... since once the playlist is loaded, playback is a foobar thing. 

Provide more info please.

**Comment by stephen147** [comment]
Sorry, it's hard to give more info. What happens if you create a normal playlist and try playing a track?

**Comment by regorxxx** [comment]
Works perfectly fine. Obviously.
Check your console log. 

Also, why do you say M3U8 don't play? Do other playlist play fine?

**Comment by stephen147** [comment]
Nothing is appearing in the console when I click on a track.

That playlist shows 5067 tracks but when I click on it, it now shows nothing. I tried to reload the playlist and it gives me this:

![image](https://github.com/regorxxx/Playlist-Manager-SMP/assets/14054664/ded719f8-4f66-4074-a900-eeccb8364cea)

Followed by this:
![image](https://github.com/regorxxx/Playlist-Manager-SMP/assets/14054664/e0aa9aba-c3a8-4d38-9246-abbe5f45e24a)

Along with this:
```
Error: Spider Monkey Panel v1.6.1-mod ({BEE593A9-3CE1-42A4-8EA0-AB09F34D20D2}: Playlist Tools: Buttons Bar v1.1.0 by regorxxx)
Script aborted by user

File: helpers_xxx_cache_volatile.js
Line: 43, Column: 22
Stack trace:
  clear@helpers_xxx_cache_volatile.js:43:22
  _recycleFile@helpers_xxx_file.js:224:31
  _list/this.updatePlaylist@playlist_manager_list.js:3400:18
```

**Comment by regorxxx** [comment]
You have to click continue, not stop. Obviously it crashes, if you stop it.

As I said, post a video. And playback is not related at all to my script anyway.

**Comment by stephen147** [comment]
It was related. This fixed it. Setting this to none worked. 

![image](https://github.com/regorxxx/Playlist-Manager-SMP/assets/14054664/b9a8d935-a476-4ab1-bfbc-56136e9628f9)

**Comment by regorxxx** [comment]
That's not a problem of my script. It's a SMP bug.
https://github.com/TheQwertiest/foo_spider_monkey_panel/issues/198

And you can play the tracks, just click play, don't use double click.

**Comment by stephen147** [comment]
Funny as I did try pressing play and that didn't work either.

**Comment by regorxxx** [comment]
It may depend on OS or version. Who knows. It's a SMP bug.

Last version has a workaround for it, it is NOT a bugfix, since I can not fix it. But problem should not happen anymore.
