### ISSUE TITLE
[BUG]  - Single left click on a playlist creates a locked duplicate

### ISSUE THREAD

**Issue by stephen147** [regorxxx/Playlist-Manager-SMP#85]
See here (The playlist is dup'd) when left clicking on an AutoPlaylist).

## Left click is set to this:

![image](https://github.com/regorxxx/Playlist-Manager-SMP/assets/14054664/81b34007-0211-41a7-97cd-4594128aa696)

## Issue (Notice the Jumping issue here also)
![new](https://github.com/regorxxx/Playlist-Manager-SMP/assets/14054664/61007a13-3c4b-4e38-a1d9-3e8fabab1f6c)

## json for this playlist:
```
	{
		"id": " (cfaca)",
		"name": "Playlist (Listening): CAR PLAYLIST R6 & R7",
		"nameId": "Playlist (Listening): CAR PLAYLIST R6 & R7 (cfaca)",
		"extension": "",
		"path": "",
		"size": 0,
		"fileSize": 0,
		"isLocked": false,
		"isAutoPlaylist": true,
		"query": "(%comment% HAS R6 OR %comment% HAS R7) OR %artist% HAS \"Arctic Monkeys\" OR %artist% HAS \"The Wombats\" OR %artist% HAS \"Boney M\"",
		"sort": "",
		"bSortForced": false,
		"category": "Playlists (General, Sets & Listening)",
		"tags": [],
		"trackTags": [],
		"limit": 0,
		"duration": 0,
		"playlist_mbid": "",
		"author": "Playlist-Manager-SMP",
		"description": "",
		"created": 1688907034937,
		"modified": 1688907034937,
		"trackSize": 0
	},
```

**Comment by regorxxx** [comment]
This is not a bug. You are using UUIDs for playlists, for whatever reason I don't understand. So when you load an auto-playlist in UI, it creates a duplicate with another UUID. I could change it to not behave it like that for Auto-playlists, but thats just the way you have set it.
