### ISSUE TITLE
[FEATURE] Write forward slashes for m3u playlists with relative paths to be compatible with Linux

### ISSUE THREAD

**Issue by marcus-at-localhost** [regorxxx/Playlist-Manager-SMP#86]
Hi, I'm trying to figure out how I can create m3u playlists for my NAS (Navidrom as streaming server).

Local:
```
M:\@library\artist\album...
M:\@playlists\test.m3u
```

I set up relatives paths for playlists and and end up with this in the m3u file:

```
..\@library\artist\album...
```

Navidrome only works with forward slashes:

```
../@library/artist/album...
```

Would it be possible to write those paths with forward slashes? Windows can read it as well (at least in relative mode)
Maybe it would make sense for the exporting of playlists, to allow the definition of a "root" prefix.

Apologies if there is already a solution for my problem and I haven't found it.

Thanks for considering.

Edit: here is a relevant discussion to my problem: https://github.com/navidrome/navidrome/issues/3511

**Comment by regorxxx** [comment]
In "Export and convert tracks" you can set the format and root for the paths in multiple ways which probably covers any use-case. 

Note you can replace slashes with any other character as you desire via TF. You will obviously have to clone/create your own preset to suit your needs, the panel offers some predefined presets as examples. **They only apply to the exported files, the original playlist files used within the panel will not be touched.** (if you only want to export the playlist file without the tracks, just cancel the converter).

I'm supposing you are already using this feature:
![image](https://github.com/user-attachments/assets/92c6ab7f-2d74-407d-94bf-dc06c865984e)

Presets are listed here:
![image](https://github.com/user-attachments/assets/5923ac70-6585-437f-a869-070d18895ecb)

TF (which is just the paths) here:
![image](https://github.com/user-attachments/assets/92a90d2e-86de-422a-8ffb-f445e60eb71d)

Finally select the playlist in contextual menu and export it:
![image](https://github.com/user-attachments/assets/ec4e1fd9-d52e-4ca0-8ace-916e82bf6fe3)

**Comment by marcus-at-localhost** [comment]
Oh that is perfect. I didn't check it out initially because I didn't want to copy/convert files. But I guess I can ignore the popups. The produced m3u file is perfect.
Thank you for the showcase.

**Comment by regorxxx** [comment]
Maybe I can add a new entry which does the same but only for the playlist file, so it's more clear for the final user:
Export and convert playlist to...
